---
x-vars:
  bitcoin_volume: &bitcoin_volume "bitcoin:/btc"
  electrs_volume: &electrs_volume "electrs_db:/electrs_db"

networks:
  btc-network:
volumes:
  bitcoin:
  electrs_db:
services:
  bitcoind:
    build:
      context: .
      dockerfile: docker/bitcoin.Dockerfile
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - *bitcoin_volume
        # - "bitcoin:/btc"
    networks:
      - btc-network
    command: >-
      ./bitcoin-0.20.1/bin/bitcoind
        -datadir=/btc
        -rpcbind=0.0.0.0:8332
        -rpcallowip=0.0.0.0/0
        -prune=0
    stop_signal: SIGINT
    stop_grace_period: 2m
  electrs:
    build:
      context: .
      dockerfile: docker/electrs.Dockerfile
    ports:
      - "50001:50001"
    volumes:
      - *bitcoin_volume
      - *electrs_volume
      #  - "bitcoin:/btc"
      #  - "electrs_db:/electrs_db"
    networks:
      - btc-network
    command: >-
      electrs -vvvv
        --daemon-rpc-addr "bitcoind:8332"
        --db-dir /electrs_db
        --timestamp
        --electrum-rpc-addr 0.0.0.0:50001
        --jsonrpc-import --cookie-file=/btc/.cookie
  js-proxy-electrs:
    build:
      context: .
      dockerfile: docker/js-proxy-electrs.Dockerfile
    ports:
      - "50002:50002"
    networks:
      - btc-network
    environment:
      ELECTRS_HOST: electrs
      ELECTRS_PORT: 50001
